In [1]:
import pandas as pd

In [2]:
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download'
url = f'{prefix}/green/green_tripdata_2020-11.csv.gz'
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-11.csv.gz'

In [11]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-11-01 00:08:23,2020-11-01 00:32:03,N,5.0,97,75,1.0,10.49,28.03,0.0,0.0,3.4,0.0,NaN,0.3,34.48,1.0,1.0,2.75
1,2.0,2020-11-01 00:23:32,2020-11-01 00:32:10,N,1.0,41,127,1.0,4.52,14.00,0.5,0.5,1.0,0.0,NaN,0.3,16.30,1.0,1.0,0.00
2,2.0,2020-11-01 00:43:14,2020-11-01 00:54:54,N,1.0,42,213,1.0,6.51,19.50,0.5,0.5,0.0,0.0,NaN,0.3,20.80,1.0,1.0,0.00
3,2.0,2020-11-01 00:33:13,2020-11-01 00:47:23,N,1.0,78,212,1.0,1.95,11.00,0.5,0.5,0.0,0.0,NaN,0.3,12.30,2.0,1.0,0.00
4,2.0,2020-11-01 00:49:28,2020-11-01 00:53:54,N,1.0,134,134,2.0,1.02,5.50,0.5,0.5,0.0,0.0,NaN,0.3,6.80,2.0,1.0,0.00

In [12]:
len(df)

88605

In [13]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-11-01 00:08:23,2020-11-01 00:32:03,N,5.0,97,75,1.0,10.49,28.03,0.0,0.0,3.40,0.00,NaN,0.3,34.48,1.0,1.0,2.75
1,2.0,2020-11-01 00:23:32,2020-11-01 00:32:10,N,1.0,41,127,1.0,4.52,14.00,0.5,0.5,1.00,0.00,NaN,0.3,16.30,1.0,1.0,0.00
2,2.0,2020-11-01 00:43:14,2020-11-01 00:54:54,N,1.0,42,213,1.0,6.51,19.50,0.5,0.5,0.00,0.00,NaN,0.3,20.80,1.0,1.0,0.00
3,2.0,2020-11-01 00:33:13,2020-11-01 00:47:23,N,1.0,78,212,1.0,1.95,11.00,0.5,0.5,0.00,0.00,NaN,0.3,12.30,2.0,1.0,0.00
4,2.0,2020-11-01 00:49:28,2020-11-01 00:53:54,N,1.0,134,134,2.0,1.02,5.50,0.5,0.5,0.00,0.00,NaN,0.3,6.80,2.0,1.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88600,NaN,2020-11-30 23:06:00,2020-11-30 23:18:00,NaN,NaN,168,235,NaN,3.99,18.52,0.0,0.0,2.75,0.00,NaN,0.3,21.57,NaN,NaN,NaN
88601,NaN,2020-11-30 23:24:00,2020-11-30 23:43:00,NaN,NaN,212,41,NaN,6.41,26.83,0.0,0.0,2.75,6.12,NaN,0.3,36.00,NaN,NaN,NaN
88602,NaN,2020-11-30 23:59:00,2020-12-01 00:32:00,NaN,NaN,37,117,NaN,11.90,46.56,0.0,0.0,2.75,2.29,NaN,0.3,51.90,NaN,NaN,NaN
88603,NaN,2020-11-30 23:53:00,2020-12-01 00:10:00,NaN,NaN,247,259,NaN,8.08,31.31,0.0,0.0,2.75,0.00,NaN,0.3,34.36,NaN,NaN,NaN
88604,NaN,2020-11-30 23:04:00,2020-11-30 23:10:00,NaN,NaN,146,226,NaN,1.42,8.41,0.0,0.0,4.78,0.00,NaN,0.3,13.49,NaN,NaN,NaN

In [17]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2020-11-01 00:08:23,2020-11-01 00:32:03,N,5.0,97,75,1.0,10.49,28.03,0.0,0.0,3.4,0.0,NaN,0.3,34.48,1.0,1.0,2.75
1,2.0,2020-11-01 00:23:32,2020-11-01 00:32:10,N,1.0,41,127,1.0,4.52,14.00,0.5,0.5,1.0,0.0,NaN,0.3,16.30,1.0,1.0,0.00
2,2.0,2020-11-01 00:43:14,2020-11-01 00:54:54,N,1.0,42,213,1.0,6.51,19.50,0.5,0.5,0.0,0.0,NaN,0.3,20.80,1.0,1.0,0.00
3,2.0,2020-11-01 00:33:13,2020-11-01 00:47:23,N,1.0,78,212,1.0,1.95,11.00,0.5,0.5,0.0,0.0,NaN,0.3,12.30,2.0,1.0,0.00
4,2.0,2020-11-01 00:49:28,2020-11-01 00:53:54,N,1.0,134,134,2.0,1.02,5.50,0.5,0.5,0.0,0.0,NaN,0.3,6.80,2.0,1.0,0.00

In [27]:
df['VendorID']

0        2.0
1        2.0
2        2.0
3        2.0
4        2.0
        ...
88600    NaN
88601    NaN
88602    NaN
88603    NaN
88604    NaN
Name: VendorID, Length: 88605, dtype: float64

In [66]:
dtype = {
    "VendorID": "float64",
    "store_and_fwd_flag": "string",
    "RatecodeID": "Int64",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "passenger_count": "float64",
    "trip_distance": "float64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "ehail_fee": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "payment_type": "float64",
    "trip_type": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime"
]

df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [67]:
df = pd.read_csv(
    url,
    dtype={"store_and_fwd_flag": "string"},
    low_memory=False,
)

In [68]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [69]:
df.head(0)

Empty DataFrame
Columns: [VendorID, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, RatecodeID, PULocationID, DOLocationID, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge]
Index: []

In [70]:
df.head(0).to_sql(name='green_tripdata_2025_11', con=engine, if_exists='replace')

0

In [71]:
print(pd.io.sql.get_schema(df, name='green_tripdata_2025_11', con=engine))

CREATE TABLE green_tripdata_2025_11 (
	"VendorID" FLOAT(53),
	lpep_pickup_datetime TEXT,
	lpep_dropoff_datetime TEXT,
	store_and_fwd_flag TEXT,
	"RatecodeID" FLOAT(53),
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	passenger_count FLOAT(53),
	trip_distance FLOAT(53),
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	ehail_fee FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	payment_type FLOAT(53),
	trip_type FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [72]:
len(df)

88605

In [73]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=20000,
)

In [74]:
for df in df_iter:
    print(len(df))

20000
20000
20000
20000
8605

In [55]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
80000,NaN,2020-11-24 14:45:00,2020-11-24 15:00:00,NaN,<NA>,78,182,NaN,2.22,18.95,0.0,0.0,2.75,0.00,<NA>,0.3,22.00,NaN,NaN,NaN
80001,NaN,2020-11-24 14:00:00,2020-11-24 14:16:00,NaN,<NA>,61,97,NaN,2.72,18.95,0.0,0.0,2.75,0.00,<NA>,0.3,22.00,NaN,NaN,NaN
80002,NaN,2020-11-24 14:53:00,2020-11-24 15:08:00,NaN,<NA>,82,95,NaN,1.58,19.06,0.0,0.0,2.75,0.00,<NA>,0.3,22.11,NaN,NaN,NaN
80003,NaN,2020-11-24 14:51:00,2020-11-24 15:13:00,NaN,<NA>,82,193,NaN,4.22,21.45,0.0,0.0,2.75,0.00,<NA>,0.3,24.50,NaN,NaN,NaN
80004,NaN,2020-11-24 14:20:00,2020-11-24 14:49:00,NaN,<NA>,89,55,NaN,4.52,29.45,0.0,0.0,2.75,0.00,<NA>,0.3,32.50,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88600,NaN,2020-11-30 23:06:00,2020-11-30 23:18:00,NaN,<NA>,168,235,NaN,3.99,18.52,0.0,0.0,2.75,0.00,<NA>,0.3,21.57,NaN,NaN,NaN
88601,NaN,2020-11-30 23:24:00,2020-11-30 23:43:00,NaN,<NA>,212,41,NaN,6.41,26.83,0.0,0.0,2.75,6.12,<NA>,0.3,36.00,NaN,NaN,NaN
88602,NaN,2020-11-30 23:59:00,2020-12-01 00:32:00,NaN,<NA>,37,117,NaN,11.90,46.56,0.0,0.0,2.75,2.29,<NA>,0.3,51.90,NaN,NaN,NaN
88603,NaN,2020-11-30 23:53:00,2020-12-01 00:10:00,NaN,<NA>,247,259,NaN,8.08,31.31,0.0,0.0,2.75,0.00,<NA>,0.3,34.36,NaN,NaN,NaN
88604,NaN,2020-11-30 23:04:00,2020-11-30 23:10:00,NaN,<NA>,146,226,NaN,1.42,8.41,0.0,0.0,4.78,0.00,<NA>,0.3,13.49,NaN,NaN,NaN

In [75]:
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=20000,
)

In [76]:
from tqdm.auto import tqdm

In [77]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='green_tripdata_2025_11', con=engine, if_exists='append')

0it [00:00, ?it/s]